### ISSUE TITLE
Time based Karma

### ISSUE THREAD

**Issue by alwanfauzan** [Rosstail/MAVEN-karma#1]
**Feature Request** 

Make karma system as time based and only active at custom range times. Make times as world time or real server time. 

This can be toggled on config file.

**Comment by Rosstail** [comment]
When you talk about karma system, do you mean karma changes on kill/attack only or some other features ?

**Comment by alwanfauzan** [comment]
> When you talk about karma system, do you mean karma changes on kill/attack only or some other features ?

Kill/Attack only, player and mob

**Comment by Rosstail** [comment]
Okay. Do you want both world time and server time or only one of them atm ?

**Comment by alwanfauzan** [comment]
Both, make that as an option, that'd be great !

**Comment by Rosstail** [comment]
Ok, I'll see to do this, pretty interresting to do

**Comment by Rosstail** [comment]
I've updated the plugin on spigot page as BETA 1.3.0, it can use on server time range. it's not compatible yet with worlds hours, but it gonna be and both can be used at the same time if needed.

**Comment by Rosstail** [comment]
Hi again !
The WORLDS time check is done from my side, gonna be updated here and on spigot.
