### ISSUE TITLE
Placeholders, up, down, etc.

### ISSUE THREAD

**Issue by thomaboehi** [Rosstail/MAVEN-karma#2]
First, thank for this nice plugin, it is useful for my server.
PlaceHolders doesn't work for me on 1.15.2

And I have a little suggestion:

I want my player to receive money when they go from tier_1 to tier_2 but I don't want them to receive this money if they fo from tier_3 to tier_2

- "<@>give <player> gold_ingot 10"

could be

- "<@><tier_up>give <player> gold_ingot 10"
- "<@><tier_down>money take <player> 10"

**Comment by Rosstail** [comment]
Hi, glad to see that my plugin is useful !

For the placeholders, I didn't add the support yet, so if you read "placeholders" it's a language abuse : gonna add it as soon as I can !

For your suggestion, I gonna try to make it as you wish :
It gonna be like this

`  tier_0:
    tier-display-name: "&f[&7Civilian&f]&r"
    tier-minimum-karma:   -4999
    tier-maximum-karma:    4999
    commands:
      - ""
    commands-on-up:
      - ""
    commands-on-down:
      - ""
`

**Comment by thomaboehi** [comment]
Thank you for your answer!

I found the placeholders on Papi Ecloud, it may be another plugin.

The commands on up and on down is a good solution.

And I wanted to submit another idea, it would be great to separate the mobs that comes from spawner, so the players can't abuse of it, what do you think?

**Comment by Rosstail** [comment]
I've done with the commands on up and down, it works perfectly ^w^

For PAPI, I gonna need some work to make it compatible with. And for the separation between mobs and mobs from spawner, i don't know if it can be done well atm. I gonna maybe separate named mobs and vanilla mobs one day.

**Comment by thomaboehi** [comment]
Thank for all!

**Comment by Rosstail** [comment]
The plugin is now updated on 1.4.2 !
https://www.spigotmc.org/resources/karma.76077/update?update=336730.

I'll close this issue for now, don't hesitate to open another one with PAPI and another with mob separation ^^
